//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktikus.Misc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.SalaryCalc = new HashSet<SalaryCalc>();
        }
    
        public int ID_Order { get; set; }
        public string Order_Status { get; set; }
        public string Order_Name { get; set; }
        public string Order_Type { get; set; }
        public Nullable<int> Current_WorkGroup { get; set; }
        public Nullable<int> Order_Manager { get; set; }
        public Nullable<int> TotalPriceOrder { get; set; }
    
        public virtual Managers Managers { get; set; }
        public virtual WorkGroup WorkGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryCalc> SalaryCalc { get; set; }
    }
}
