//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktikus.Misc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryCalc
    {
        public int ID_Ticket { get; set; }
        public int ID_Of_Order { get; set; }
        public int ID_Of_Manager { get; set; }
        public Nullable<int> Salary_For_Manager { get; set; }
        public int ID_Of_Workgroup { get; set; }
        public Nullable<int> Salary_For_Workgroup { get; set; }
    
        public virtual Managers Managers { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual WorkGroup WorkGroup { get; set; }
    }
}
